apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deployment 
  name: nginx-deployment
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000
  selector:
    app: nginx-deployment
  type: NodePort
status:
  loadBalancer: {}
    

    